# 线上配置文件
server:
  port: 8500
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 86400
spring:
  application:
    name: apiandbi-backend

  # 数据库配置
  # 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.112.58:3306/intelliAPI
    username: zzRd
    password: cqj1211@
  # Redis 配置
  # 需替换配置
  redis:
    database: 2
    host: 8.134.112.58
    port: 6379
    timeout: 5000
    password: 181399
  session:
    store-type: redis
    timeout: 86400
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

  rabbitmq:
    username: image
    password: image
    host: 8.134.112.58
    port: 5672

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: ''
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
image:
  spark:
    client:
      api-key: 0ad9891ef06fc7e5888b7641ace89a72
      appid: 3dd67985
      api-secret: MTJkNmRhYjRiM2RjYWMxNjI5YjgxYTcy
  yucongming:
    client:
      access-key: p6k7eo4btts7d83o6c4h0ak26mbrlvn1
      secret-key: 8fct7wq6x7x4qyyo0a246of87sqv8t9z
  qwen:
    client:
      apikey: sk-56bd3bbc269d43939d41cea923145e49

dubbo:
  application:
    name: dubbo-springboot-demo-provider
    qos-port: 22231
  protocol:
    name: dubbo
    port: 22223
  registry:
    id: nacos-registry
    address: nacos://8.134.112.58:8848